before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    main: .
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    binary: songlink
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

brews:
  - repository:
      owner: marcusziade
      name: homebrew-songlink-cli
    folder: Formula
    homepage: "https://github.com/marcusziade/songlink-cli"
    description: "CLI for retrieving Songlink and Spotify links for music URLs"
    license: "MIT"
    test: |
      system "#{bin}/songlink", "-h"
    install: |
      bin.install "songlink"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch

# Disabled signing as we don't have GPG keys configured in CI
# signs:
#   - artifacts: checksum
