name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (vX.Y.Z format)'
        required: true
        type: string

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: stable

      - name: Validate version
        run: |
          VERSION=${{ github.event.inputs.version }}
          if ! [[ $VERSION =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Version must be in format vX.Y.Z"
            exit 1
          fi
          echo "Version is valid: $VERSION"
          git tag $VERSION || (echo "Tag already exists" && exit 1)

      - name: Install cosign
        uses: sigstore/cosign-installer@v3.1.2

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}