name: Release

on:
  push:
    branches:
      - master
    tags:
      - '*.*.*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: stable

      - name: Check if we should release
        id: should_release
        run: |
          # Only run on tag pushes
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            echo "should_release=true" >> $GITHUB_OUTPUT
            echo "This is a tag push, will create release"
          else
            echo "should_release=false" >> $GITHUB_OUTPUT
            echo "This is a branch push, skipping release"
          fi

      - name: Install cosign
        if: steps.should_release.outputs.should_release == 'true'
        uses: sigstore/cosign-installer@v3.1.2

      - name: Run GoReleaser
        if: steps.should_release.outputs.should_release == 'true'
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}